project_id = "icczrurozqotpvjpirqk"

[functions.recolor-room]
verify_jwt = false

[functions.suggest-colors]
verify_jwt = false

[functions.sync-1c]
verify_jwt = false

[functions.import-tints]
verify_jwt = false